version: 2.1

jobs:
  # Build cli and run test
  build:
    docker:
      - image: rust:1.64.0-slim
    working_directory: ~/cli
    steps:
      - checkout
      - run: cargo --version
      - run:
          name: Run Tests
          command: "cargo test"
      - run:
          name: Build
          command: "cargo build --release"
      - persist_to_workspace:
          root: target
          paths:
            - ./release/dctl
  # Release on tags (see workflow))    
  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./target/release
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$(dctl --version)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./target/release/dctl

workflows:
  version: 2
  main:
    jobs:
      - build
      - publish-github-release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/