version: 2.1

jobs:
  build:
    docker:
      - image: cimg/rust:1.63.0
    steps:
      - checkout
      - run: cargo --version
      - run:
          name: Run Tests
          command: "cd cli && cargo test"
