version: 2.1

jobs:
  build:
    docker:
      - image: rust:1.64.0-slim
    steps:
      - checkout
      - run: cargo --version
      - run:
          name: Run Tests
          command: "cd cli && cargo test"
