version: 2.1

jobs:
  tests:
    docker:
      - image: rust:1.64.0-slim
    steps:
      - checkout
      - run:
          name: Run Tests
          command: cd cli && cargo test
  build:
    docker:
      - image: rust:1.64.0-slim
    steps:
      - checkout
      - run:
          name: Build
          command: cd cli && cargo build --release
      - persist_to_workspace:
          root: cli/target
          paths:
            - release
  github_release:
    docker:
      - image: cibuilds/github:0.13.0
    steps:
      - attach_workspace:
          at: work
      - run:
          name: "Release version"
          command: ls -al work/release/dctl
      - run:
          name: "Publish Release on GitHub"
          command: |
            gh release create $CIRCLE_TAG \
              -t "Release $CIRCLE_TAG" \
              -n "Release $CIRCLE_TAG" \
              -R $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME \
              work/release/dctl
              
workflows:
  version: 2
  test_build_release:
    jobs:
      - tests:
          filters:
            tags:
              only: /.*/
      - build:
          requires:
            - tests
          filters:
            tags:
              only: /.*/
      - check_release:
          type: approval
          requires:
            - tests
            - build
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - github_release:
          requires:
            - check_release
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/

