version: 2.1

jobs:
  # Run tests
  tests:
    docker:
      - image: rust:1.64.0-slim
    steps:
      - checkout
      - run:
          name: Run Tests
          command: cd cli && cargo test
  # Run build, store dctl
  build:
    docker:
      - image: rust:1.64.0-slim
    steps:
      - checkout
      - run:
          name: Build
          command: cd cli && cargo build --release
      - persist_to_workspace:
          root: cli
          paths:
            - ./target/release/dctl
  # Release on tags (see workflow))    
  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./target/release
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$(dctl --version)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./target/release/dctl

workflows:
  version: 2
  test_build_release:
    jobs:
      - tests:
          filters:
            tags:
              only: /.*/
      - build:
          requires:
            - tests
          filters:
            tags:
              only: /.*/
      - publish-github-release:
          type: approval
          requires:
            - build
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
