workflows:
  version: 2
  main:
    jobs:
      - build: ~
      - publish-github-release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/