[package]
name = "dctl"
version = "1.3.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.30.0", features = ["full"] }
async-trait = { version = "0.1.72" }
eyre = { version = "0.6.8" }
clap = { version = "4.3.21", features = ["cargo"] }
clap_complete = { version = "4.3.2" }
toml = { version =  "0.7.6" }
dotenv = { version = "0.15.0" }
serde = { version = "1.0.167", features = ["derive"] }
serde_json = { version = "1.0.104" }
shellexpand = { version = "3.1.0" }
tabled = { version = "0.14.0" }
mockall = { version = "0.11.4" }
version = { version = "3.0.0" }