[package]
name = "dctl"
version = "1.5.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.45.1", features = ["full"] }
async-trait = { version = "0.1.88" }
eyre = { version = "0.6.12" }
clap = { version = "4.5.39", features = ["cargo"] }
clap_complete = { version = "4.5.52" }
toml = { version =  "0.8.22" }
dotenv = { version = "0.15.0" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0.140" }
shellexpand = { version = "3.1.0" }
tabled = { version = "0.20.0" }
mockall = { version = "0.13.1" }
version = { version = "3.0.0" }


[profile.release]
lto = "thin"
opt-level = "z"
panic = "abort"
strip = "debuginfo"