[package]
name = "dctl"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = { version = "0.6.8" }
clap = { version = "4.0.11", features = ["derive", "cargo"] }
toml = { version =  "0.5.9" }
dotenv = { version = "0.15.0" }
serde = { version = "1.0.145", features = ["derive" ] }
shellexpand = { version = "2.1.2" }
tabled = { version = "0.9.0" }