[package]
name = "dctl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.17", features = ["derive", "cargo"] }
toml = { version =  "0.5.9" }
dotenv = { version = "0.15.0" }
serde = { version = "1.0.144" }