[package]
name = "dctl"
version = "1.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.26.0", features = ["full"] }
async-trait = { version = "0.1.67" }
eyre = { version = "0.6.8" }
clap = { version = "4.1.10", features = ["cargo"] }
clap_complete = { version = "4.1.5" }
toml = { version =  "0.7.3" }
dotenv = { version = "0.15.0" }
serde = { version = "1.0.157", features = ["derive"] }
serde_json = { version = "1.0.94" }
shellexpand = { version = "3.0.0" }
tabled = { version = "0.10.0" }
mockall = { version = "0.11.3" }
version = { version = "3.0.0" }