[package]
name = "dctl"
version = "1.3.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.29.1", features = ["full"] }
async-trait = { version = "0.1.71" }
eyre = { version = "0.6.8" }
clap = { version = "4.3.11", features = ["cargo"] }
clap_complete = { version = "4.3.2" }
toml = { version =  "0.7.6" }
dotenv = { version = "0.15.0" }
serde = { version = "1.0.167", features = ["derive"] }
serde_json = { version = "1.0.100" }
shellexpand = { version = "3.1.0" }
tabled = { version = "0.12.2" }
mockall = { version = "0.11.4" }
version = { version = "3.0.0" }