[package]
name = "dctl"
version = "1.5.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.36.0", features = ["full"] }
async-trait = { version = "0.1.77" }
eyre = { version = "0.6.12" }
clap = { version = "4.5.1", features = ["cargo"] }
clap_complete = { version = "4.5.1" }
cliclack = { version = "0.1.12" }
toml = { version =  "0.8.10" }
dotenv = { version = "0.15.0" }
serde = { version = "1.0.196", features = ["derive"] }
serde_json = { version = "1.0.113" }
shellexpand = { version = "3.1.0" }
tabled = { version = "0.15.0" }
mockall = { version = "0.12.1" }
version = { version = "3.0.0" }
