[package]
name = "dctl"
version = "1.4.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.34.0", features = ["full"] }
async-trait = { version = "0.1.74" }
eyre = { version = "0.6.9" }
clap = { version = "4.4.10", features = ["cargo"] }
clap_complete = { version = "4.4.4" }
toml = { version =  "0.8.8" }
dotenv = { version = "0.15.0" }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = { version = "1.0.108" }
shellexpand = { version = "3.1.0" }
tabled = { version = "0.14.0" }
mockall = { version = "0.11.4" }
version = { version = "3.0.0" }